# Generated by Django 2.2.2 on 2020-03-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='count',
        ),
    ]
