# Generated by Django 2.2.2 on 2020-03-24 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('-pk',), 'verbose_name_plural': 'History'},
        ),
    ]
